### PR TITLE
GetFollowing init

### PR DESCRIPTION
**Pull request by Bengejd**
**Description**: This allows you to request your following list using the sessionid_ss cookie.

I wasn't entirely sure the best way to handle initializing the sessionid_ss value, so I put it into the initialization of the API, but if there is a better place for it, I'm willing to change it as necessary. 

**Example usage:**

```
api = TikTokApi.get_instance(sessionid_ss='YOUR_SESSIONID_SS_COOKIE_HERE')
    following = api.getFollowing(custom_verifyFp="CUSTOM_VERIFYFP_TOKEN", custom_did='CUSTOM_DID_TOKEN', count=199)
```
This will recursively iterate through your following list, and retrieve all of the available accounts that **YOU** are following, with their full profile details (username, bio, avatar, etc...). Once it reaches the end, it will return all of the accounts in a list format.

No idea what the API endpoint is to retrieve your followers, but I'm sure it's a very similar method.

Should close issue #459  if accepted.

### CODE REVIEW

**Comment by Bengejd** [comment]
One thing I've noticed during testing is that this will not in fact get you your full following list. My assumption for the cause of this is because TikTok doesn't automatically unfollow accounts that are banned (as they still show up in the mobile app list). So if you are following 4,000 accounts, and it only brings back 3950 in the results, I am assuming that it's not showing you the banned accounts, but more testing will have to be done to verify that.

**Comment by davidteather** [comment]
One quick change do you mind moving it to the tiktokuser.py file? I'm trying to keep all user-specific functionality in that file.

Feel free to add a static variable to that class of type TikTokApi that you can use to sign your URL instead of the self.getData line.

Thanks!

**Comment by Bengejd** [comment]
For sure, I can make that happen!

**Comment by duhaime** [comment]
ping @Bengejd thanks for this! Any chance on that last commit / update to handle the merge conflicts?

**Comment by bertin0** [comment]
If I wanted to continue this work how would I go about doing that? New PR?

**Comment by davidteather** [comment]
@bertin0 Think you should be able to fork `Bengejd:getFollowing_PR` from there you should be able to theoretically make a PR into this repository

**Pull request closed without merging**
