### PR TITLE
Removed Host and Authority from the requests to prefent the 403 error…

### PR DESCRIPTION
**Pull request by BeatRoy**
This pull request fixes the error in issue #751 and #750 by removing the host headers from the requests done with the requests lib.

The error fixed in this pull request:
```
ERROR:root:Tiktok response: 
 <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Bad request.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: IeGDfwk6_DQAbAm_pK1GAI1hrszMdKzJIjv0BbfsneGU8p59Gcnv4w==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```

### CODE REVIEW

**Comment by Alex-Laparra** [comment]
fixed it for me, thanks! david needs to see this

**Comment by DigitalApeMedia-DS** [comment]
@BeatRoy many thanks, works!

**Comment by davidteather** [comment]
Thanks for finding a solution! I don't have too much time to test right now because my school still has classes this week, but I'll try to test soon. My only concern is potentially might make the methods that aren't HTTP fetches work less reliably, but not sure if they check it.

**Comment by BeatRoy** [comment]
> 

https://stackoverflow.com/questions/57770557/missing-host-header-in-http-requests-from-the-requests-python-library
The conclusion is that python `requests` does not add a host header but the underlying `http` module does so it is not required to send it with the request.

**Comment by davidteather** [comment]
Yeah I’m aware it’s not required and won’t work if it is set for urls like tiktok.com/@therock or something like that, but the host header is set when the tiktok frontend makes requests to their backend (you can check network inspector for all the headers set). But good find :)

**Comment by Silver-birder** [comment]
I'm looking forward to the merge! :)

**Comment by chachoe** [comment]
Excuse me, i´m having this problem, and i would like to install this fix, but i don´t know how to do it :(

Someone can help me to install this branch?

**Comment by davidteather** [comment]
Looks good merging :) thank you

**Pull request merged**
