### PR TITLE
Make API work with an already running event loop

### LINKED ISSUE #123: Sentence: Add async
Hello everyone who reads this issue. I would like to ask to add async to this api, I just have to copy corrections from the new commit to change my code and this is not very convenient. RapidApi also has a limitation in the basic version for requests, for this reason I can not use it. Thank you very much for reading my suggestion.

### PR DESCRIPTION
**Pull request by crazygmr101**
Related #123 
Related #115 ?

Uses a separate thread to run the event loop for TikTokApi, since only one event loop can be ran at a time. This allows the Api to be used in applications that already use the event loop, i.e. Discord bots

### CODE REVIEW

**Comment by crazygmr101** [comment]
Note, the library is still mainly sync in how it's called - a bit of a rewrite would be required to change that

**Comment by crazygmr101** [comment]
Looks like this also might fix #146

**Comment by davidteather** [comment]
Travis is failing probably because the loop is never closed

**Comment by crazygmr101** [comment]
> Travis is failing probably because the loop is never closed

Fair point, I'm on the way to work but I can fix that later tonight then

**Comment by crazygmr101** [comment]
Waiting on https://github.com/davidteather/TikTok-Api/pull/198/commits/955e90602cfa7261e38ffd3bb193955b5d7814cf - https://github.com/davidteather/TikTok-Api/pull/198/commits/65cb4fd19c1744adff9a76659210688aea37e0f6 passed but didn't actually let me close the loop in my bot

**Comment by davidteather** [comment]
I resolved conflicts in #232 sorry it took me so long to test.

**Pull request closed without merging**
