### PR TITLE
Make API work with an already running event loop #198

### PR DESCRIPTION
**Pull request by davidteather**
This is #198 but with conflicts resolved

### CODE REVIEW

**Comment by crazygmr101** [comment]
No worries. I could continue work on a fully async fork, if you'd like, and save trouble here :)

**Comment by davidteather** [comment]
That would be much appreciated, thanks!

**Comment by davidteather** [comment]
@crazygmr101 I'm not sure why, but when I resolved issue between our branches the package has been throwing some weird errors. It doesn't break the application as it only seems to be an issue when the TikTokApi instance is used for the last time it throws
```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/python/3.5.6/lib/python3.5/asyncio/base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "/opt/python/3.5.6/lib/python3.5/asyncio/base_events.py", line 408, in run_forever
    raise RuntimeError('This event loop is already running')
```

It seems to throw 4 of these errors for each time the TikTokApi class is destroyed

**Comment by crazygmr101** [comment]
Might be something I missed, I'll check it out tonight

**Comment by davidteather** [comment]
Thanks! Not sure if it was your branch's issue, because I did test it. I think I would've noticed if it threw an error. I'll keep looking

**Comment by crazygmr101** [comment]
Alrighty. If ya need to contact me, discord is fastest, crazygmr101#5324.

**Pull request merged**
